Find-and-replace docker-compose docker compose

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -374,36 +374,36 @@ jobs:
           path: ./dev/minio/data/faasm
           key: ${{ env.CPU_MODEL }}-s3-data-${{ secrets.CACHE_VERSION }}
       # Setup
-      - name: "Start docker-compose"
-        run: docker-compose up -d --scale worker=2 nginx
+      - name: "Start docker compose"
+        run: docker compose up -d --scale worker=2 nginx
       # This can fail when the container isn't ready, so we want to retry
       - name: "Wait for upload server to be available"
         run: |
-          (echo "Attempt 1" && docker-compose exec -T upload /usr/local/code/faasm/deploy/local/wait_for_upload.sh localhost 8002) || \
-          (sleep 30s && echo "Attempt 2" && docker-compose exec -T upload /usr/local/code/faasm/deploy/local/wait_for_upload.sh localhost 8002) || \
-          (sleep 30s && echo "Attempt 3" && docker-compose exec -T upload /usr/local/code/faasm/deploy/local/wait_for_upload.sh localhost 8002) || \
-          (echo "Wait for upload failed after retries" && docker-compose logs upload && exit 1)
+          (echo "Attempt 1" && docker compose exec -T upload /usr/local/code/faasm/deploy/local/wait_for_upload.sh localhost 8002) || \
+          (sleep 30s && echo "Attempt 2" && docker compose exec -T upload /usr/local/code/faasm/deploy/local/wait_for_upload.sh localhost 8002) || \
+          (sleep 30s && echo "Attempt 3" && docker compose exec -T upload /usr/local/code/faasm/deploy/local/wait_for_upload.sh localhost 8002) || \
+          (echo "Wait for upload failed after retries" && docker compose logs upload && exit 1)
       # Function upload
       - name: "Build and upload cpp function"
-        run: docker-compose run -T cpp inv func demo hello func.upload demo hello
+        run: docker compose run -T cpp inv func demo hello func.upload demo hello
       - name: "Build and upload python function"
-        run: docker-compose run -T python inv func func.upload func.uploadpy hello
+        run: docker compose run -T python inv func func.upload func.uploadpy hello
       # Function invocation
       - name: "Invoke cpp function"
-        run: docker-compose run -T cpp inv func.invoke demo hello | tee output_1.log
+        run: docker compose run -T cpp inv func.invoke demo hello | tee output_1.log
       - name: "Invoke python hello function"
-        run: docker-compose run -T python inv func.invoke python hello
+        run: docker compose run -T python inv func.invoke python hello
       # Re-invocation of same function with different code after flush
       - name: "Flush workers"
-        run: docker-compose run -T cpp inv func.flush
+        run: docker compose run -T cpp inv func.flush
       - name: "Build echo function and upload in place of hello function"
         run: ./deploy/local/replace_hello_with_echo.sh
       - name: "Invoke cpp function"
-        run: docker-compose run -T cpp inv func.invoke demo hello | tee output_2.log
+        run: docker compose run -T cpp inv func.invoke demo hello | tee output_2.log
       - name: "Check both outputs are different"
         run: (cmp output_1.log output_2.log && exit 1 || exit 0)
       # Print logs and finish
-      - name: "Docker-compose logs"
-        run: docker-compose logs
-      - name: "Stop docker-compose"
-        run: docker-compose down
+      - name: "docker compose logs"
+        run: docker compose logs
+      - name: "Stop docker compose"
+        run: docker compose down
